name: deployment to server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA4KfJjmfSYOfOFrRpR2fsxL/kA2z/LXd5rx/V7CPOe0VRxIz9vIIg
wsm+w5zJ01k8o7JcnfLKfoUC4daifo6WXHyEnndm6iJE9E4V4KuTr8Xbi12UkglN3/EHbO
+iW4HfzcGT4Oid7aF49XPlbk9PUBZdLbfzWZeMjWgSuYHoLKCX6eob1vrFWENo/5MsS4+u
Ff6OB5x7rsnH3lAKK1Ytw9zrIU0yZKIUauIQnONTdMmeAXAXei3gk+uYWMvw3Mm0VXUmIw
A98/tXJw8Bf+yPSRdeUdRKYDFbopaWjKKWH0jty2I74NkHZQOfbIE2QH+rk52H3jRTSuEX
XSLIaObei4T4SyuPGwonp4oCaeaVzy3VEWbyCe6WlyiLVn1KpumSNxH+QWHDRIvrTjjMBY
kVbkXv7tpLUgDJyHjXaiaLLBcx/lxkHqVEm+5K8pnSdrI2gTnrShMGoC6gEZvfKl4Rits9
VpyrdeHoucTIIRXRZs7YaH191HIyjMt8L3o2BkbtAAAFkENNeqxDTXqsAAAAB3NzaC1yc2
EAAAGBAOCnyY5n0mDnzha0aUdn7MS/5ANs/y13ea8f1ewjzntFUcSM/byCIMLJvsOcydNZ
PKOyXJ3yyn6FAuHWon6Ollx8hJ53ZuoiRPROFeCrk6/F24tdlJIJTd/xB2zvoluB383Bk+
Done2hePVz5W5PT1AWXS2381mXjI1oErmB6Cygl+nqG9b6xVhDaP+TLEuPrhX+jgece67J
x95QCitWLcPc6yFNMmSiFGriEJzjU3TJngFwF3ot4JPrmFjL8NzJtFV1JiMAPfP7VycPAX
/sj0kXXlHUSmAxW6KWloyilh9I7ctiO+DZB2UDn2yBNkB/q5Odh940U0rhF10iyGjm3ouE
+EsrjxsKJ6eKAmnmlc8t1RFm8gnulpcoi1Z9SqbpkjcR/kFhw0SL6044zAWJFW5F7+7aS1
IAych412omiywXMf5cZB6lRJvuSvKZ0nayNoE560oTBqAuoBGb3ypeEYrbPVacq3Xh6LnE
yCEV0WbO2Gh9fdRyMozLfC96NgZG7QAAAAMBAAEAAAGACs2WwC3W7IkJHIdlbqUdOiLeJJ
oHtViC9fxqbZYVNlFRisma5Ac/6w4HieGOxQaMB3Uqxf+oZCgiSNjo7HwP1/e26uXkAYtP
VI4yuCCYFAJIOe3wmIsw/v1YtZDadlsK95qA8XZOLeCvb+I4XLMcpcXFik7HuX2zqRMhn2
ETWJ4KYBm9Z/ucJM/tCyk5HpMUtIMOsmgAfJnAbjzcGFRnE/2aIvpS24r9v1wKn3jBCSMu
4XPR9TKik4pnQ5HfDcb3OXNlCMkmwMdKwB49Yd0mKn2dxQVLpG0vS6U0bhtsI/bBKPrMsp
Wp94taiGX8v0TcP8nxGK5NOL4QRW5ZcOQcD+0FTJeSwicB3RKIbSRpPAGXkdJ9LGKebbDU
cglz3Cnz8WHvUM3AogHXXpb3gFUhIco7eTEKQSDbbKO3DtNPzlTQ0reJF2M2JNXZKSCs+T
DGWNcKG7SBEVv4rIR94rXRApWupCxT7i/g7PF9QvnpPhR7f/J0zPeuIrQexmpbyYGBAAAA
wQDUju38nTSNMc6FvoHjg047zQakJZXgFC9i2GWVZXyKjyLATHGgvvBSvOM4tGwJYMj2JI
GNkVMnvlvq1xJKEk4+auP7vI5Ww029uoAOkv1BgpV4TRoGPmnahW4eJQyRC1kXMV0Nw0J+
pOWe1B9Za0G0n7Fwh63nEUEifcPpvyT36OhGtykvmjKOXPK5rmyA615rBtu0kO+vBcyKto
V9gpVHi2ExD7jUcKPryMLx+7gVfzQsLxWASFxfSjRh/MnlMTwAAADBAPur4UbnJsQp2xHw
TeX0G3JJ4ymZ0GEri6+4u4bzyQudhfAr6ENg5fqBurre9p9fd5xJqO1x5QeUVyi9EqBbS1
ysOgLAgtypQ6EV55/I4dITlnskMLo7pawDj8cvrCCPS/AVfbHg0KBXt9GGwBCh+GbiXgRh
dblXYDJB4e1gdSX7tHmD/ofI8+GDV8R2VfqrpyKPF5gT82EfUv9O9YxeURvHBdSNyxLb/5
xqfG0YoFalo78+war/b77B5c3IS4TMLQAAAMEA5IT0bR8EbZdHvH9d2oGReiK2SETR/fsS
XnUPrN5XgQPln6xM7EZU5lF5KfnimVGhdB+wbPhgSZzX9xk9yRGw/fBSmhDaTwzGScMPul
RsGxdF/Gd40p6wZVX0OBweAfYGzvorxsamOPC1QmzpXlSI3qmcR3CiaDLFInLunr0uOBhk
F0akoYSVSJKsGtwJBnbHICtMWCVFs7RcLm7/NVD3B35eGsZzVTBN2xMzqVVueX/fdJH6EP
VptCUBMpxVLF3BAAAAGFN0YW5sZXl5eUBzMTMuc2VydjAwLmNvbQEC
-----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Pull changes on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_PATH }} && ~/bin/php ~/bin/composer install --no-dev --optimize-autoloader"

    - name: Run migrations
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_PATH }} && ~/bin/php artisan migrate --force"

    - name: Vite build
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_PATH }} && yarn run build && rm -rf node_modules"

    - name: Optimize
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_PATH }} && ~/bin/php artisan optimize:clear && ~/bin/php artisan filament:optimize-clear"
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_PATH }} && ~/bin/php artisan optimize && ~/bin/php artisan filament:optimize"
